#!/bin/bash

set -o vi
umask 0007

# ----------------------------------------------------------------------
# --- Variables
#
# General
export TERM="xterm-256color"
export HRULEWIDTH=73
export EDITOR_PREFIX="nvim"
export EDITOR="nvim"
export VISUAL="nvim"
export CLICOLOR=1
# export GPG_TTY="$(tty)"
export PAGER="less"
export HISTFILE="${XDG_DATA_HOME}/history"
export GNUPGHOME="${XDG_CONFIG_HOME}/gnupg"
export INPUTRC="${XDG_CONFIG_HOME}/shell/inputrc"
export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME}/npm"
export HISTCONTROL=ignoreboth
export LESSHISTFILE="-"

# User
export USER="$(whoami)"
export GITUSER="${USER}"
export DOT="${HOME}/.dot"
export SCRIPTS="${HOME}/.local/bin"
export WORKSPACE="${HOME}/Workspace"
export REPOS="${WORKSPACE}/repos"
export GHREPOS="${REPOS}/github.com"
export GLREPOS="${REPOS}/gitlab.com"
export NOTES="${XDG_DATA_HOME}/notes"
export TMPDIR="/tmp"

# XDG
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CURRENT_DESKTOP=sway
export XDG_DATA_DIRS="${HOME}/.local/share:${HOME}/.nix-profile/share:${HOME}/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/"
export XDG_DATA_HOME="${HOME}/.local/share"
export XDG_DESKTOP_DIR="${HOME}/Desktop"
export XDG_DOCUMENTS_DIR="${HOME}/Documents"
export XDG_DOWNLOAD_DIR="${HOME}/Downloads"
export XDG_GAMES_DIR="${HOME}/Games"
export XDG_MUSIC_DIR="${HOME}/Music"
export XDG_PICTURES_DIR="${HOME}/Pictures"
export XDG_PUBLICSHARE_DIR="${HOME}/Public"
export XDG_SESSION_DESKTOP=sway
export XDG_TEMPLATES_DIR="${HOME}/Templates"
export XDG_VIDEOS_DIR="${HOME}/Videos"

# Nix
NIXOS_OZONE_WL=1

# QT
export QT_QPA_PLATFORM=wayland

# Lynx
export LYNX_CFG="${XDG_CONFIG_HOME}/lynx/lynx.cfg"
export LYNX_LSS="${XDG_CONFIG_HOME}/lynx/lynx.lss"

# Rust
export CARGO_HOME="${XDG_DATA_HOME}/cargo"
export RUSTUP_HOME="${XDG_DATA_HOME}/rust"

# Go
export GOPATH="${XDG_DATA_HOME}/go"
export GOBIN="${HOME}/.local/bin"

# Docker
export DOCKER_CONTENT_TRUST=0

# PNPM
export PNPM_HOME="${XDG_DATA_HOME}/pnpm"

# Kubernetes
export KUBECONFIG="${HOME}/.kube/config"

# ----------------------------------------------------------------------
# --- Aliases
alias '?'='duck'
alias '??'='google'
alias 'cd..'='cd ..'
alias ls="/bin/ls -la --color"
alias chmox="chmod u+x"
alias temp="cd $(mktemp -d)"
alias pn="pnpm"

# ----------------------------------------------------------------------
# --- Functions
function __exists() {
    type "$1" &>/dev/null
}

function reload() {
    source "${HOME}/.bashrc"
}

clone() {
    cd "$(bash "${HOME}/.local/bin/clone" "$@" | tail -n 1)" || return 1
}

function pathappend() {
    declare arg
    for arg in "$@"; do
        test -d "$arg" || continue
        PATH=${PATH//":$arg:"/:}
        PATH=${PATH/#"$arg:"/}
        PATH=${PATH/%":$arg"/}
        export PATH="${PATH:+"$PATH:"}$arg"
    done
}

function pathprepend() {
    for arg in "$@"; do
        test -d "$arg" || continue
        PATH=${PATH//:"$arg:"/:}
        PATH=${PATH/#"$arg:"/}
        PATH=${PATH/%":$arg"/}
        export PATH="$arg${PATH:+":${PATH}"}"
    done
}

# ----------------------------------------------------------------------
# --- PATH and CDPATH
pathprepend \
    "${PNPM_HOME}" \
    "${GOBIN}" \
    "${HOME}/.nix-profile/bin" \
    "${HOME}/.local/bin"

pathappend \
    /usr/local/bin \
    /usr/local/sbin \
    /usr/local/games \
    /usr/games \
    /usr/sbin \
    /usr/bin \
    /snap/bin \
    /sbin \
    /bin

export CDPATH=".:${REPOS}:${GHREPOS}:${GHREPOS}/${USER}:${GLREPOS}:${GLREPOS}/${USER}:${WORKSPACE}:${HOME}"

# ----------------------------------------------------------------------
# --- Prompt
__prompt() {
    local username='\u' hostname='\h' character='❯' status="$?" status_color \
        git_branch format directory_prefix directory directory_suffix \
        o='\[\e[1;30m\]' r='\[\e[1;31m\]' g='\[\e[1;32m\]' \
        y='\[\e[1;33m\]' b='\[\e[1;34m\]' m='\[\e[1;35m\]' \
        c='\[\e[1;36m\]' w='\[\e[1;37m\]' d='\[\e[0m\]'

    status_color=${g}
    directory="${b}${PWD##*/}${d}"
    git_branch="$(git branch --show-current 2>/dev/null)"

    [[ "${status}" != 0 ]] && status_color="${r}"
    [[ "${PWD}" == / ]] && directory="${b}/${d}"
    [[ "${PWD}" == "$HOME" ]] && directory="${b}~${d}"
    [[ "${PWD}" != $HOME* ]] && directory_suffix="🔒"
    [[ -n "${git_branch}" ]] && git_branch=" on${m}  ${git_branch}${d}"

    format="\n${directory_prefix}${directory}${directory_suffix}${git_branch} \n${status_color}${character} ${d}"
    PS1="${format}"
}

PROMPT_COMMAND="__prompt"

# ----------------------------------------------------------------------
# --- Direnv
if __exists direnv; then
    eval "$(direnv hook bash)"
fi

# ----------------------------------------------------------------------
# --- Dircolors
if __exists dircolors; then
    if [[ -r "${XDG_CONFIG_HOME}/shell/dircolors" ]]; then
        eval "$(dircolors -b "${XDG_CONFIG_HOME}/shell/dircolors")"
    else
        eval "$(dircolors -b)"
    fi
fi

# ----------------------------------------------------------------------
# --- Bash completion
if [[ -r "/usr/share/bash-completion/bash_completion" ]]; then
    source "/usr/share/bash-completion/bash_completion"
fi

# ----------------------------------------------------------------------
# --- Personal environment
if [[ -r "${XDG_CONFIG_HOME}/shell/personal" ]]; then
    source "${XDG_CONFIG_HOME}/shell/personal"
fi
