local M = {}

M.servers = {
    "ansiblels",
    "astro",
    "bashls",
    "clangd",
    "cmake",
    "cssls",
    "cssmodules_ls",
    "dagger",
    "diagnosticls",
    "docker_compose_language_service",
    "dockerls",
    "emmet_ls",
    "eslint",
    "golangci_lint_ls",
    "gopls",
    "graphql",
    "html",
    "jsonls",
    "lua_ls",
    "prismals",
    "rnix",
    "rust_analyzer",
    "sqlls",
    "tailwindcss",
    "taplo",
    "terraformls",
    "tflint",
    "tsserver",
    "vimls",
    "volar",
    "yamlls",
}

return M
