{
  allowUnfree = true;
  packageOverrides = pkgs:
    with pkgs; {
      user = pkgs.buildEnv {
        name = "user-packages";
        paths = [
          age
          albert
          awscli2
          bind
          bitwarden
          bitwarden-cli
          cargo
          chezmoi
          clippy
          curl
          delve
          direnv
          fd
          fluxcd
          fuzzel
          gammastep
          gcc
          gh
          git
          gnumake
          go
          goaccess
          gzip
          hadolint
          helm
          htop
          jq
          kind
          kubeconform
          kubectl
          kustomize
          lm_sensors
          lsof
          lynx
          mako
          mpv
          neofetch
          neovim
          netlify-cli
          nettools
          nix-direnv
          nixfmt
          nmap
          nodejs
          packer
          pandoc
          pciutils
          perl
          podman
          podman-compose
          pulumi-bin
          remmina
          ripgrep
          rsync
          rust-analyzer
          rustc
          rustfmt
          shellcheck
          smartmontools
          sops
          sshpass
          stack
          strace
          stylua
          swayimg
          sysfsutils
          terraform
          tmux
          traceroute
          tree
          tree-sitter
          unrar
          unzip
          ventoy
          waybar
          weechat
          wget
          whois
          wl-clipboard
          yq
          zathura
          zip
        ];
        # pathsToLink = [ "/bin" "/share" ];
      };
    };
}
